// lib/seedData.js
import mongoose from "mongoose";
import { connectToDatabase } from "./db.js";

export async function seedDatabaseIfEmpty(force = false) {
  try {
    const reportsConn = await connectToDatabase("reports");
    const reportsCount = await reportsConn.db.collection("reports").countDocuments();

    console.log(`Current reports in database: ${reportsCount}`);

    // Check if seeding is needed
    if (!force && reportsCount >= 10) {
      console.log("Database already has sufficient reports, skipping seed.");
      return { seeded: false, count: reportsCount };
    }

    console.log("Seeding full municipal data, wards, authorities & realistic grievance reports...");

    // 1. Seed Municipalities & Wards in 'municipalities' db
    const muniConn = await connectToDatabase("municipalities");
    let kmc = await muniConn.db.collection("municipals").findOne({ name: "Kolkata Municipal Corporation" });
    if (!kmc) {
      const muniResult = await muniConn.db.collection("municipals").insertOne({
        name: "Kolkata Municipal Corporation",
        fileName: "kolkata_wards.geojson",
        municipalId: "111110000000",
        lastAssignedId: 111110000010,
        other_municipal_data: {
          city: "Kolkata",
          state: "West Bengal",
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      kmc = { _id: muniResult.insertedId, name: "Kolkata Municipal Corporation" };
      console.log("✅ Seeded Kolkata Municipal Corporation");
    }

    // Seed Wards (Wards 1 through 12) with representative polygons around Kolkata [lng, lat]
    const wardCount = await muniConn.db.collection("wards").countDocuments();
    if (wardCount < 5 || force) {
      await muniConn.db.collection("wards").deleteMany({});
      const wardDocs = [];
      const baseCoords = [
        { ward: 1, center: [88.3700, 22.6100], name: "Cossipore / Ward 1" },
        { ward: 2, center: [88.3800, 22.6000], name: "Belgachia / Ward 2" },
        { ward: 3, center: [88.3750, 22.5900], name: "Shyambazar / Ward 3" },
        { ward: 4, center: [88.3650, 22.5800], name: "Maniktala / Ward 4" },
        { ward: 5, center: [88.3639, 22.5726], name: "College Street / Ward 5" },
        { ward: 6, center: [88.3500, 22.5650], name: "Esplanade / BBD Bagh / Ward 6" },
        { ward: 7, center: [88.3600, 22.5500], name: "Park Circus / Ward 7" },
        { ward: 8, center: [88.3550, 22.5400], name: "Ballygunge / Ward 8" },
        { ward: 9, center: [88.3450, 22.5300], name: "Bhowanipore / Ward 9" },
        { ward: 10, center: [88.3500, 22.5100], name: "Alipore / Ward 10" },
        { ward: 11, center: [88.3650, 22.5000], name: "Jadavpur / Ward 11" },
        { ward: 12, center: [88.4312, 22.5785], name: "Salt Lake Sector V / Ward 12" },
      ];

      for (const w of baseCoords) {
        const [lng, lat] = w.center;
        const delta = 0.02;
        wardDocs.push({
          ward_number: w.ward,
          municipal_id: kmc._id,
          geometry: {
            type: "Polygon",
            coordinates: [[
              [lng - delta, lat - delta],
              [lng + delta, lat - delta],
              [lng + delta, lat + delta],
              [lng - delta, lat + delta],
              [lng - delta, lat - delta],
            ]],
          },
        });
      }
      await muniConn.db.collection("wards").insertMany(wardDocs);
      console.log(`✅ Seeded ${wardDocs.length} wards with geospatial polygons`);
    }

    // 2. Seed AdministrativeHeads in 'Administrative' db
    const adminConn = await connectToDatabase("Administrative");
    let adminHead = await adminConn.db.collection("AdministrativeHeads").findOne({ authority: "Low" });
    if (!adminHead) {
      const inserted = await adminConn.db.collection("AdministrativeHeads").insertOne({
        fullName: "Subhash Chandra Ghosh",
        email: "kmc.officer.ward8@kolkatamunicipal.gov.in",
        phone: 9830123456,
        age: 44,
        designation: "Ward Grievance & Inspection Officer",
        authority: "Low",
        municipality: "Kolkata Municipal Corporation",
        municipalId: kmc._id,
        userId: 10001,
        password: "hashed_dummy_password",
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      adminHead = { _id: inserted.insertedId, fullName: "Subhash Chandra Ghosh", authority: "Low" };
      console.log("✅ Seeded Ward Grievance Officer");
    }

    // 3. User Rupayan Dey (ID: 6abfd43fc587f1434154d128)
    const rupayanUserId = new mongoose.Types.ObjectId("6abfd43fc587f1434154d128");

    // Clear old sparse reports to avoid collisions
    await reportsConn.db.collection("reports").deleteMany({});

    // Generate 24 realistic municipal reports across the realistic grievance lifecycle
    const seedReports = [
      // 1. SUBMITTED
      {
        ticketId: "CIVIC-20261003-00124",
        Title: "Garbage Overflowing Outside Community Market",
        category: "Waste Management",
        Description: "Community waste bins overflowing for 4 consecutive days near Salt Lake Sector V gate 2. Emitting foul odor and attracting stray animals.",
        severity: "Medium",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.4312, 22.5785] },
        address: "Sector V, Gate 2, Salt Lake",
        locality: "Salt Lake Sector V",
        ward: "Ward 12",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/garbage_thumb.jpg",
        mediaUrl: "/images/garbage_thumb.jpg",
        status: "submitted",
        department: "Solid Waste Management",
        assignedTo: adminHead._id,
        assignedOfficer: "Subhash Chandra Ghosh",
        assignedRole: "Low",
        sendToMunicipality: true,
        verified: false,
        mlPredictedSeverity: "Medium",
        mlConfidence: 0.91,
        sla: {
          targetHours: 48,
          dueAt: new Date(Date.now() + 42 * 60 * 60 * 1000),
          breached: false,
        },
        history: [
          {
            action: "created",
            actorId: rupayanUserId,
            actorName: "Rupayan Dey",
            actorRole: "user",
            timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
            notes: "Report registered and ticket CIVIC-20261003-00124 generated.",
          },
        ],
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },

      // 2. ACKNOWLEDGED
      {
        ticketId: "CIVIC-20261003-00118",
        Title: "Underground Water Pipeline Leakage at Crossroad",
        category: "Water Supply",
        Description: "Continuous water gushing out of cracked municipal water main, causing waterlogging on the roadway.",
        severity: "High",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3600, 22.5500] },
        address: "Crossroad 4, Park Circus",
        locality: "Park Circus",
        ward: "Ward 7",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        mediaUrl: "/images/street_issue_thumb.jpg",
        status: "acknowledged",
        department: "Water Supply & Distribution",
        assignedTo: adminHead._id,
        assignedOfficer: "Subhash Chandra Ghosh",
        sendToMunicipality: true,
        verified: false,
        sla: {
          targetHours: 24,
          dueAt: new Date(Date.now() + 18 * 60 * 60 * 1000),
          breached: false,
        },
        history: [
          {
            action: "created",
            actorId: rupayanUserId,
            actorName: "Rupayan Dey",
            actorRole: "user",
            timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
            notes: "Report submitted by citizen.",
          },
          {
            action: "acknowledged",
            actorName: "Civic Saathi Dispatch",
            actorRole: "system",
            timestamp: new Date(Date.now() - 5.8 * 60 * 60 * 1000),
            notes: "System acknowledged complaint. SMS/Email notification sent to citizen.",
          },
        ],
        createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 5.8 * 60 * 60 * 1000),
      },

      // 3. TRIAGED
      {
        ticketId: "CIVIC-20261002-00095",
        Title: "Street Light Failure on Main Avenue",
        category: "Street Lights",
        Description: "Sodium vapor street lamp pole #42 not turning on for 3 nights, pitch dark section on public road.",
        severity: "Medium",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3550, 22.5400] },
        address: "Ballygunge Circular Road",
        locality: "Ballygunge",
        ward: "Ward 8",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_light_thumb.jpg",
        mediaUrl: "/images/street_light_thumb.jpg",
        status: "triaged",
        department: "Electrical / Street Lighting",
        assignedTo: adminHead._id,
        assignedOfficer: "Subhash Chandra Ghosh",
        sendToMunicipality: true,
        verified: true,
        mlPredictedSeverity: "Medium",
        mlConfidence: 0.94,
        sla: {
          targetHours: 48,
          dueAt: new Date(Date.now() + 32 * 60 * 60 * 1000),
          breached: false,
        },
        history: [
          {
            action: "created",
            actorId: rupayanUserId,
            actorName: "Rupayan Dey",
            actorRole: "user",
            timestamp: new Date(Date.now() - 14 * 60 * 60 * 1000),
            notes: "Report submitted by citizen.",
          },
          {
            action: "acknowledged",
            actorName: "Civic Saathi Automated Dispatch",
            actorRole: "system",
            timestamp: new Date(Date.now() - 13.9 * 60 * 60 * 1000),
            notes: "Complaint acknowledged.",
          },
          {
            action: "triaged",
            actorName: "Civic AI Engine",
            actorRole: "system",
            timestamp: new Date(Date.now() - 13.8 * 60 * 60 * 1000),
            notes: "AI validated: Location Ward 8, Category 'Street Lights', Severity 'Medium' (94% confidence). No duplicate found.",
          },
        ],
        createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 13.8 * 60 * 60 * 1000),
      },

      // 4. UNDER_REVIEW
      {
        ticketId: "CIVIC-20261002-00088",
        Title: "Deep Asphalt Potholes Near School Crossing",
        category: "Potholes",
        Description: "Cluster of multiple deep potholes causing dangerous braking for school buses and cyclists.",
        severity: "High",
        ReporterName: "Ananya Mukherjee",
        locationCoordinates: { type: "Point", coordinates: [88.3650, 22.5800] },
        address: "Near Maniktala High School",
        locality: "Maniktala",
        ward: "Ward 4",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "under_review",
        department: "Public Works Department",
        assignedTo: adminHead._id,
        assignedOfficer: "Subhash Chandra Ghosh",
        sendToMunicipality: true,
        verified: true,
        sla: {
          targetHours: 48,
          dueAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
          breached: false,
        },
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000), notes: "Submitted by citizen." },
          { action: "acknowledged", actorRole: "system", timestamp: new Date(Date.now() - 19.9 * 60 * 60 * 1000), notes: "Ticket generated." },
          { action: "triaged", actorRole: "system", timestamp: new Date(Date.now() - 19.8 * 60 * 60 * 1000), notes: "Geocoded to Ward 4 PWD." },
          { action: "reviewed", actorName: "Subhash Chandra Ghosh", actorRole: "admin", timestamp: new Date(Date.now() - 15 * 60 * 60 * 1000), notes: "Municipal Officer reviewing complaint validity." },
        ],
        createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 15 * 60 * 60 * 1000),
      },

      // 5. NEEDS_INFORMATION
      {
        ticketId: "CIVIC-20261001-00072",
        Title: "Damaged Drainage Slab Over Pedestrian Footpath",
        category: "Sanitation",
        Description: "Cracked concrete slab with exposed rebars, hazard for senior citizens.",
        severity: "Medium",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3500, 22.5100] },
        address: "Alipore Park Road",
        locality: "Alipore",
        ward: "Ward 10",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "needs_information",
        clarificationRequest: "Please provide a clearer close-up photograph showing whether the drain underneath is blocked or structurally intact.",
        department: "Civil Drainage Engineering",
        assignedTo: adminHead._id,
        assignedOfficer: "Subhash Chandra Ghosh",
        sendToMunicipality: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 36 * 60 * 60 * 1000), notes: "Report registered." },
          { action: "under_review", actorRole: "admin", timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000), notes: "Reviewed by Officer." },
          { action: "clarification_requested", actorName: "Subhash Chandra Ghosh", actorRole: "admin", timestamp: new Date(Date.now() - 28 * 60 * 60 * 1000), notes: "Officer requested: clearer close-up photograph of drain slab." },
        ],
        createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 28 * 60 * 60 * 1000),
      },

      // 6. ACCEPTED & ASSIGNED
      {
        ticketId: "CIVIC-20261001-00065",
        Title: "Broken Median Road Divider Causing Head-on Hazards",
        category: "Road & Transport",
        Description: "Vehicle crash shattered concrete median barrier, concrete chunks scattered on road.",
        severity: "High",
        ReporterName: "Sourav Ganguly",
        locationCoordinates: { type: "Point", coordinates: [88.3550, 22.5400] },
        address: "Syed Amir Ali Avenue",
        locality: "Ballygunge",
        ward: "Ward 8",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "assigned",
        department: "Public Works Department",
        assignedDepartment: "PWD Road Maintenance Wing",
        assignedTeam: "Zone 3 Rapid Action Team",
        assignedOfficer: "Er. P. K. Banerjee",
        assignedAt: new Date(Date.now() - 22 * 60 * 60 * 1000),
        sendToMunicipality: true,
        verified: true,
        sla: {
          targetHours: 36,
          dueAt: new Date(Date.now() + 14 * 60 * 60 * 1000),
          breached: false,
        },
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 40 * 60 * 60 * 1000), notes: "Report registered." },
          { action: "accepted", actorName: "Subhash Chandra Ghosh", actorRole: "admin", timestamp: new Date(Date.now() - 25 * 60 * 60 * 1000), notes: "Jurisdiction confirmed. Accepted for execution." },
          { action: "assigned", actorName: "PWD Central", actorRole: "admin", timestamp: new Date(Date.now() - 22 * 60 * 60 * 1000), notes: "Assigned to PWD Road Maintenance Wing, Er. P. K. Banerjee." },
        ],
        createdAt: new Date(Date.now() - 40 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 22 * 60 * 60 * 1000),
      },

      // 7. FIELD_INSPECTION
      {
        ticketId: "CIVIC-20260930-00054",
        Title: "Severe Road Surface Subsidence After Heavy Rain",
        category: "Road Damage",
        Description: "Road asphalt sinking noticeably near storm drain inlet.",
        severity: "High",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3639, 22.5726] },
        address: "Bidhan Sarani / College Street",
        locality: "College Street",
        ward: "Ward 5",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "inspection",
        department: "Public Works Department",
        inspectionNotes: "Site inspected by Junior Engineer at 11:30 AM. Soil underneath asphalt washed away due to pipe joint defect. Immediate shoring required.",
        inspectedBy: "Er. P. K. Banerjee",
        inspectedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
        sendToMunicipality: true,
        verified: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 50 * 60 * 60 * 1000), notes: "Submitted by citizen." },
          { action: "accepted", actorRole: "admin", timestamp: new Date(Date.now() - 42 * 60 * 60 * 1000), notes: "Accepted by KMC." },
          { action: "inspection_dispatched", actorRole: "admin", timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000), notes: "Field engineer dispatched to site." },
          { action: "inspected", actorName: "Er. P. K. Banerjee", actorRole: "field_officer", timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000), notes: "Physical site inspection completed. Confirmed sub-surface void." },
        ],
        createdAt: new Date(Date.now() - 50 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },

      // 8. ACTION_PLANNED
      {
        ticketId: "CIVIC-20260929-00049",
        Title: "Stormwater Drain Desilting Required Before Monsoon",
        category: "Sanitation",
        Description: "Drainage canal filled with plastic silt, water flowing at less than 20% capacity.",
        severity: "Medium",
        ReporterName: "Bratin Das",
        locationCoordinates: { type: "Point", coordinates: [88.3450, 22.5300] },
        address: "Harish Mukherjee Road",
        locality: "Bhowanipore",
        ward: "Ward 9",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "action_planned",
        department: "Sewerage & Drainage",
        assignedTeam: "Mechanical Excavation Unit 2",
        sendToMunicipality: true,
        verified: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000), notes: "Registered." },
          { action: "inspected", actorRole: "field_officer", timestamp: new Date(Date.now() - 55 * 60 * 60 * 1000), notes: "Canal survey completed." },
          { action: "action_planned", actorName: "S&D Department", actorRole: "admin", timestamp: new Date(Date.now() - 36 * 60 * 60 * 1000), notes: "Action planned: Mechanical desilting machine allotted for 05-Oct work window." },
        ],
        createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
      },

      // 9. IN_PROGRESS
      {
        ticketId: "CIVIC-20260928-00041",
        Title: "Bitumen Road Resurfacing on Central Crossing",
        category: "Road & Transport",
        Description: "Resurfacing damaged 200-meter asphalt patch.",
        severity: "High",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3650, 22.5000] },
        address: "Raja SC Mullick Road",
        locality: "Jadavpur",
        ward: "Ward 11",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "in_progress",
        department: "Public Works Department",
        assignedTeam: "Road Patch Crew #4",
        sendToMunicipality: true,
        verified: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 96 * 60 * 60 * 1000), notes: "Registered by citizen." },
          { action: "accepted", actorRole: "admin", timestamp: new Date(Date.now() - 80 * 60 * 60 * 1000), notes: "Accepted." },
          { action: "assigned", actorRole: "admin", timestamp: new Date(Date.now() - 60 * 60 * 1000), notes: "Assigned to Road Patch Crew." },
          { action: "work_started", actorName: "Site Supervisor", actorRole: "field_officer", timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), notes: "Cold mix asphalt laid, steam roller operating on site." },
        ],
        createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
      },

      // 10. ON_HOLD
      {
        ticketId: "CIVIC-20260927-00035",
        Title: "Water Main Valve Chamber Repair",
        category: "Water Supply",
        Description: "Chamber brickwork collapsed near junction.",
        severity: "Medium",
        ReporterName: "Tanmoy Sen",
        locationCoordinates: { type: "Point", coordinates: [88.3750, 22.5900] },
        address: "Shyambazar Five-Point Crossing",
        locality: "Shyambazar",
        ward: "Ward 3",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "on_hold",
        holdReason: "Awaiting nighttime traffic police clearance for lane closure and water line shutoff window.",
        expectedResumeDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        department: "Water Supply",
        sendToMunicipality: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 110 * 60 * 60 * 1000), notes: "Submitted." },
          { action: "in_progress", actorRole: "field_officer", timestamp: new Date(Date.now() - 70 * 60 * 60 * 1000), notes: "Initial excavation done." },
          { action: "on_hold", actorName: "Water Supply Wing", actorRole: "admin", timestamp: new Date(Date.now() - 40 * 60 * 60 * 1000), notes: "Placed on hold: Awaiting Kolkata Traffic Police NOC for nighttime lane diversion." },
        ],
        createdAt: new Date(Date.now() - 110 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 40 * 60 * 60 * 1000),
      },

      // 11. ESCALATED (SLA Breached)
      {
        ticketId: "CIVIC-20260926-00028",
        Title: "Hazardous Overflowing Sewage on Hospital Access Lane",
        category: "Sanitation",
        Description: "Raw sewage spilling onto road right outside nursing home gate. Biohazard for patients.",
        severity: "High",
        ReporterName: "Dr. K. Sengupta",
        locationCoordinates: { type: "Point", coordinates: [88.3700, 22.6100] },
        address: "Near North City Clinic, Cossipore",
        locality: "Cossipore",
        ward: "Ward 1",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/garbage_thumb.jpg",
        status: "escalated",
        department: "Drainage & Sewerage",
        sla: {
          targetHours: 24,
          dueAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
          breached: true,
          breachedAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
        },
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 60 * 60 * 60 * 1000), notes: "Submitted." },
          { action: "assigned", actorRole: "admin", timestamp: new Date(Date.now() - 50 * 60 * 60 * 1000), notes: "Assigned to Ward Sewerage Inspector." },
          { action: "sla_breached", actorRole: "system", timestamp: new Date(Date.now() - 36 * 60 * 60 * 1000), notes: "System SLA monitor detected 24h breach without resolution." },
          { action: "escalated", actorName: "Municipal Commissioner Vigilance", actorRole: "admin", timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000), notes: "Case auto-escalated to Deputy Municipal Commissioner due to healthcare facility proximity." },
        ],
        createdAt: new Date(Date.now() - 60 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
      },

      // 12. RESOLUTION_SUBMITTED
      {
        ticketId: "CIVIC-20260925-00021",
        Title: "Faulty LED Street Lighting Fixture Replacement",
        category: "Street Lights",
        Description: "Flickering high-mast lighting causing disorientation.",
        severity: "Low",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3500, 22.5650] },
        address: "Esplanade Central Crossing",
        locality: "Esplanade",
        ward: "Ward 6",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_light_thumb.jpg",
        status: "resolution_submitted",
        department: "Electrical / Street Lighting",
        resolutionNotes: "Replaced 150W LED driver and luminaire. Functionality verified with automated timer switch.",
        resolutionProofImages: ["/images/street_light_thumb.jpg"],
        resolvedBy: "Field Tech B. Naskar",
        resolvedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
        sendToMunicipality: true,
        verified: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 140 * 60 * 60 * 1000), notes: "Submitted." },
          { action: "in_progress", actorRole: "field_officer", timestamp: new Date(Date.now() - 40 * 60 * 60 * 1000), notes: "Technician on hydraulic ladder repairing light." },
          { action: "resolution_submitted", actorName: "Field Tech B. Naskar", actorRole: "field_officer", timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000), notes: "Work finished. Proof uploaded for supervisor signoff." },
        ],
        createdAt: new Date(Date.now() - 140 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
      },

      // 13. VERIFICATION
      {
        ticketId: "CIVIC-20260924-00015",
        Title: "Damaged Pothole Patching on Bus Route",
        category: "Potholes",
        Description: "Large pothole in middle of lane repaired.",
        severity: "Medium",
        ReporterName: "Debashis Roy",
        locationCoordinates: { type: "Point", coordinates: [88.3800, 22.6000] },
        address: "Belgachia Road",
        locality: "Belgachia",
        ward: "Ward 2",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "verification",
        department: "Public Works Department",
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 160 * 60 * 60 * 1000), notes: "Registered." },
          { action: "resolution_submitted", actorRole: "field_officer", timestamp: new Date(Date.now() - 14 * 60 * 60 * 1000), notes: "Road crew submitted patch completion." },
          { action: "verification_started", actorName: "Assistant Engineer Roy", actorRole: "supervisor", timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000), notes: "Supervisor visiting site for compaction and level test." },
        ],
        createdAt: new Date(Date.now() - 160 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
      },

      // 14. REWORK_REQUIRED
      {
        ticketId: "CIVIC-20260923-00011",
        Title: "Improper Asphalt Leveling on Pothole Patch",
        category: "Potholes",
        Description: "Contractor dumped bitumen without leveling, creating bump.",
        severity: "Medium",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3550, 22.5400] },
        address: "Ballygunge Circular Road",
        locality: "Ballygunge",
        ward: "Ward 8",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "rework_required",
        department: "Public Works Department",
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 190 * 60 * 60 * 1000), notes: "Submitted." },
          { action: "resolution_submitted", actorRole: "field_officer", timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000), notes: "Contractor marked done." },
          { action: "verification_failed", actorName: "Quality Inspector", actorRole: "supervisor", timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000), notes: "Quality audit rejected patch: 3cm uneven surface. Returned to crew for resurfacing." },
        ],
        createdAt: new Date(Date.now() - 190 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
      },

      // 15. RESOLVED
      {
        ticketId: "CIVIC-20260920-00008",
        Title: "Bio-Waste Removal from Primary School Boundary",
        category: "Waste Management",
        Description: "Garbage bins completely cleared and area sanitized with lime powder.",
        severity: "High",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3750, 22.5900] },
        address: "Ward 3 Community Compactor",
        locality: "Shyambazar",
        ward: "Ward 3",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/garbage_thumb.jpg",
        status: "resolved",
        department: "Solid Waste Management",
        resolutionNotes: "Dump cleared with mechanical compactor vehicle. Lime powder disinfectant sprayed.",
        resolvedAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
        sendToMunicipality: true,
        verified: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 250 * 60 * 60 * 1000), notes: "Submitted by citizen." },
          { action: "inspected", actorRole: "field_officer", timestamp: new Date(Date.now() - 200 * 60 * 60 * 1000), notes: "Site verified." },
          { action: "work_completed", actorRole: "municipality", timestamp: new Date(Date.now() - 50 * 60 * 60 * 1000), notes: "Waste collected and disposed." },
          { action: "resolved", actorName: "Ward 3 Sanitary Inspector", actorRole: "admin", timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000), notes: "Supervisor verified clearance. Citizen notified." },
        ],
        createdAt: new Date(Date.now() - 250 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
      },

      // 16. CLOSED (Citizen Satisfied Feedback)
      {
        ticketId: "CIVIC-20260915-00003",
        Title: "Dangerous Open Manhole Cover Replaced",
        category: "Sanitation",
        Description: "Heavy ductile iron manhole cover installed with flush asphalt ring.",
        severity: "High",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3639, 22.5726] },
        address: "Surya Sen Street",
        locality: "College Street",
        ward: "Ward 5",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "closed",
        department: "Sewerage & Drainage",
        citizenFeedback: {
          rating: 5,
          satisfied: true,
          comment: "Prompt replacement within 24 hours of report. Road is completely safe now. Thank you KMC!",
          submittedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        },
        resolvedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
        closedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        sendToMunicipality: true,
        verified: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000), notes: "Submitted." },
          { action: "resolved", actorRole: "admin", timestamp: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000), notes: "New cover fitted." },
          { action: "feedback_received", actorName: "Rupayan Dey", actorRole: "user", timestamp: new Date(Date.now() - 10 * 24 * 60 * 1000), notes: "Citizen rated 5 stars: Highly satisfied." },
          { action: "closed", actorName: "System", actorRole: "system", timestamp: new Date(Date.now() - 10 * 24 * 60 * 1000), notes: "Ticket closed with full citizen satisfaction." },
        ],
        createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 10 * 24 * 60 * 1000),
      },

      // 17. REOPENED
      {
        ticketId: "CIVIC-20260910-00001",
        Title: "Garbage Re-accumulated at Cleared Corner",
        category: "Waste Management",
        Description: "Garbage removed 3 days ago, but open dumping resumed as no waste bin was installed.",
        severity: "Medium",
        ReporterName: "Rupayan Dey",
        reporterId: rupayanUserId,
        reporterEmail: "rupayandey134@gmail.com",
        locationCoordinates: { type: "Point", coordinates: [88.3600, 22.5500] },
        address: "Park Circus 7-Point",
        locality: "Park Circus",
        ward: "Ward 7",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/garbage_thumb.jpg",
        status: "reopened",
        department: "Solid Waste Management",
        citizenFeedback: {
          rating: 2,
          satisfied: false,
          comment: "Garbage came back the next morning because commercial shops have nowhere to dump. We need a proper bin, not just one-time sweep!",
          submittedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        },
        sendToMunicipality: true,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000), notes: "Submitted." },
          { action: "resolved", actorRole: "admin", timestamp: new Date(Date.now() - 16 * 24 * 60 * 1000), notes: "Marked resolved." },
          { action: "reopened", actorName: "Rupayan Dey", actorRole: "user", timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000), notes: "Citizen rejected resolution: Issue recurred. Re-opened for permanent dustbin installation." },
        ],
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 15 * 24 * 60 * 1000),
      },

      // 18. REJECTED
      {
        ticketId: "CIVIC-20260905-00002",
        Title: "Private Residential Complex Internal Pipeline Leak",
        category: "Water Supply",
        Description: "Internal piping leakage inside apartment building compound.",
        severity: "Low",
        ReporterName: "Sanjay Singhal",
        locationCoordinates: { type: "Point", coordinates: [88.4312, 22.5785] },
        address: "Tower 4, Green Valley Enclave",
        locality: "Salt Lake Sector V",
        ward: "Ward 12",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "rejected",
        rejectionReason: "Issue falls inside private cooperative housing society premises and is outside municipal public works jurisdiction. Please contact society welfare association.",
        rejectedBy: "Subhash Chandra Ghosh",
        sendToMunicipality: false,
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000), notes: "Submitted." },
          { action: "rejected", actorName: "Subhash Chandra Ghosh", actorRole: "admin", timestamp: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000), notes: "Rejection: Private society internal infrastructure outside KMC jurisdiction." },
        ],
        createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000),
      },

      // 19. DUPLICATE
      {
        ticketId: "CIVIC-20261001-00068",
        Title: "Pothole Outside Maniktala School",
        category: "Potholes",
        Description: "Large pothole on Maniktala road.",
        severity: "High",
        ReporterName: "Pritam Pal",
        locationCoordinates: { type: "Point", coordinates: [88.3650, 22.5800] },
        address: "Near Maniktala High School",
        locality: "Maniktala",
        ward: "Ward 4",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "duplicate",
        duplicateOf: "CIVIC-20261002-00088",
        department: "Public Works Department",
        history: [
          { action: "created", actorRole: "user", timestamp: new Date(Date.now() - 22 * 60 * 60 * 1000), notes: "Submitted." },
          { action: "duplicate_detected", actorRole: "system", timestamp: new Date(Date.now() - 21.8 * 60 * 60 * 1000), notes: "Merged with primary ticket CIVIC-20261002-00088 (exact location & issue match)." },
        ],
        createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000),
        updatedAt: new Date(Date.now() - 21.8 * 60 * 60 * 1000),
      },

      // 20-25. Historical resolved & closed reports across May, June, July, August 2026
      {
        ticketId: "CIVIC-20260814-00091",
        Title: "Stormwater Inlet Blockage on Central Avenue",
        category: "Sanitation",
        Description: "Drainage grates completely blocked by construction sand.",
        severity: "High",
        ReporterName: "B. K. Ghosh",
        locationCoordinates: { type: "Point", coordinates: [88.3639, 22.5726] },
        address: "CR Avenue, Ward 5",
        locality: "College Street",
        ward: "Ward 5",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "closed",
        department: "Sewerage & Drainage",
        resolvedAt: new Date("2026-08-16T14:30:00Z"),
        closedAt: new Date("2026-08-18T10:00:00Z"),
        createdAt: new Date("2026-08-14T09:15:00Z"),
        updatedAt: new Date("2026-08-18T10:00:00Z"),
      },
      {
        ticketId: "CIVIC-20260802-00078",
        Title: "Damaged Sodium Lamp on Ward 6 Lane",
        category: "Street Lights",
        Description: "Street lamp bulb shattered during squall.",
        severity: "Medium",
        ReporterName: "S. Roy",
        locationCoordinates: { type: "Point", coordinates: [88.3500, 22.5650] },
        address: "Ward 6 Lane, Esplanade",
        locality: "Esplanade",
        ward: "Ward 6",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_light_thumb.jpg",
        status: "resolved",
        department: "Electrical / Street Lighting",
        resolvedAt: new Date("2026-08-04T18:00:00Z"),
        createdAt: new Date("2026-08-02T11:00:00Z"),
        updatedAt: new Date("2026-08-04T18:00:00Z"),
      },
      {
        ticketId: "CIVIC-20260719-00062",
        Title: "Heavy Potholes on Diamond Harbour Road",
        category: "Potholes",
        Description: "Road crater 1.5m wide causing vehicle axle damage.",
        severity: "High",
        ReporterName: "A. Bose",
        locationCoordinates: { type: "Point", coordinates: [88.3500, 22.5100] },
        address: "Diamond Harbour Road, Ward 10",
        locality: "Alipore",
        ward: "Ward 10",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "closed",
        department: "Public Works Department",
        resolvedAt: new Date("2026-07-22T16:00:00Z"),
        closedAt: new Date("2026-07-24T12:00:00Z"),
        createdAt: new Date("2026-07-19T08:30:00Z"),
        updatedAt: new Date("2026-07-24T12:00:00Z"),
      },
      {
        ticketId: "CIVIC-20260705-00055",
        Title: "Overflowing Garbage Vat Near Fish Market",
        category: "Waste Management",
        Description: "Commercial organic waste rotting under sun.",
        severity: "High",
        ReporterName: "M. Das",
        locationCoordinates: { type: "Point", coordinates: [88.3750, 22.5900] },
        address: "Shyambazar Market, Ward 3",
        locality: "Shyambazar",
        ward: "Ward 3",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/garbage_thumb.jpg",
        status: "resolved",
        department: "Solid Waste Management",
        resolvedAt: new Date("2026-07-06T12:00:00Z"),
        createdAt: new Date("2026-07-05T10:00:00Z"),
        updatedAt: new Date("2026-07-06T12:00:00Z"),
      },
      {
        ticketId: "CIVIC-20260621-00044",
        Title: "Underground Filtered Water Pipe Leakage",
        category: "Water Supply",
        Description: "High pressure potable water stream bubbling up from asphalt.",
        severity: "High",
        ReporterName: "K. Sen",
        locationCoordinates: { type: "Point", coordinates: [88.3600, 22.5500] },
        address: "Park Circus, Ward 7",
        locality: "Park Circus",
        ward: "Ward 7",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "closed",
        department: "Water Supply",
        resolvedAt: new Date("2026-06-23T11:00:00Z"),
        closedAt: new Date("2026-06-25T14:00:00Z"),
        createdAt: new Date("2026-06-21T07:45:00Z"),
        updatedAt: new Date("2026-06-25T14:00:00Z"),
      },
      {
        ticketId: "CIVIC-20260515-00030",
        Title: "Asphalt Cracking and Rutting on Bus Stop",
        category: "Road Damage",
        Description: "Heavy vehicle tyre ruts deforming road grade.",
        severity: "Medium",
        ReporterName: "T. Banerjee",
        locationCoordinates: { type: "Point", coordinates: [88.3550, 22.5400] },
        address: "Ballygunge Phari, Ward 8",
        locality: "Ballygunge",
        ward: "Ward 8",
        municipalityName: "Kolkata Municipal Corporation",
        municipalityId: kmc._id,
        image: "/images/street_issue_thumb.jpg",
        status: "closed",
        department: "Public Works Department",
        resolvedAt: new Date("2026-05-18T15:00:00Z"),
        closedAt: new Date("2026-05-20T10:00:00Z"),
        createdAt: new Date("2026-05-15T09:00:00Z"),
        updatedAt: new Date("2026-05-20T10:00:00Z"),
      },
    ];

    await reportsConn.db.collection("reports").insertMany(seedReports);
    console.log(`✅ Successfully inserted ${seedReports.length} comprehensive grievance lifecycle reports into MongoDB!`);

    return { seeded: true, count: seedReports.length };
  } catch (err) {
    console.error("Database seed error:", err);
    throw err;
  }
}
